### PR TITLE
Update members.py

### PR DESCRIPTION
**Pull request by Soapy7261**
use type hints, remove members that are too new

not tested yet, dont merge

### CODE REVIEW

**Comment by Soapy7261** [comment]
also not finished

**Comment by ToothyDev** [comment]
Hm, not sure I care when members were made though
I mean yes usually its trolls, but this leaves no way to override it, and would lock discord newcomers and (genuine) alt users to a week of waiting

**Comment by Soapy7261** [comment]
Hm, would 24h make more sense then?

**Comment by Soapy7261** [comment]
Since waiting a max of 24h wouldn't be that bad

**Comment by ToothyDev** [comment]
They are kicked after 2 weeks for inactivity anyway, or kicked by the bot checker right away - i dont think this is necessary

**Comment by Soapy7261** [comment]
Fair, but art scammers, y'know

**Comment by Soapy7261** [comment]
i think most are just hacked old accounts anyway so maybe not

**Pull request closed without merging**
